version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  

  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"

  discountdb:
    container_name: discountdb
    environment: 
      - POSTGRES_USER:admin
      - POSTGRES_PASSWORD:admin12345
      - POSTGRES_DB:discountdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data 




  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=abdullah_shaqaliah@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=Pop@12345
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  Portainer:
    container_name: Portainer
    restart: always
    ports:
        - "9000:9000"
        - "8080:8000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
     - catalogdb
    ports:
      - "8000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CasheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on: 
        - basketdb
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=host.docker.internal\\SQLEXPRESS,1433;UID=sa;PWD=123456;Database=DiscountDb"
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=host.docker.internal\\SQLEXPRESS,1433;UID=sa;PWD=123456;Database=DiscountDb"
    ports:
      - "8003:80"

